# Версия в соответствии с движком https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"
# Установка PHP + подключение локальной папки
services:
  php:
    build: ./dockerfiles/php
    volumes:
      - './www:/var/www/html'
    ports:
      - 80:80
# Установка Nginx + подключение локальной папки + конфиг файл

# Установка базы MariaDb + проброс портов + файлы базы сохраняем в локальной папке проекта
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./my-db:/var/lib/mysql

# Установка phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

